server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
    open-in-view: false